<?php
/**
 * Created by PhpStorm.
 * User: snguyenone
 * Date: 10/1/18
 * Time: 10:30
 */

namespace App\Controller\Component;

use Cake\Controller\Component;
use Cake\Mailer\Email;

class AppMailComponent extends Component
{
	protected $type = 'gmail';
	protected $options = [
		'from'       => '[Website Chainos Demo]',
		'subject'    => '[Website Chainos Demo]',
		'message'    => __METHOD__,
		'format'     => 'html',
		'template'   => ''
	];
	protected $emailClass;
	
	/**
	 * @param array $config
	 */
	public function initialize(array $config)
	{
		parent::initialize($config); // TODO: Change the autogenerated stub
		$this->setTypeConfig();
		$this->setClassEmail(new Email($this->getTypeConfig()));
	}
	
	/**
	 * @param Email|null $emailClass
	 * @return mixed
	 */
	public function setClassEmail(Email $emailClass)
	{
		$this->emailClass = $emailClass;
		
		return $this;
	}
	
	/**
	 * @return mixed
	 */
	public function getClassEmail()
	{
		return $this->emailClass;
	}
	
	/**
	 * @param string $type
	 * @return $this
	 */
	public function setTypeConfig($type = 'gmail')
	{
		$this->type = $type;
		
		return $this;
	}
	
	/**
	 * @return string
	 */
	public function getTypeConfig()
	{
		return $this->type;
	}
	
	/**
	 * @param array $options
	 * @return $this
	 */
	public function setOptions(array $options = [])
	{
		if (!isset($options['to'])) {
			new \Exception('Please set address send to.');
		}
		
		$this->options = array_merge($this->options, $options);
		
		return $this;
	}
	
	/**
	 * @param null $name
	 * @return array|mixed
	 */
	public function getOptions($name = null)
	{
		return $name == null ? $this->options : $this->options[$name];
	}
	
	/**
	 * @param null $data
	 * @return boolean
	 */
	public function sendMail($data = null)
	{
		try {
			return $this->getClassEmail()->setFrom(
				[
					$this->getOptions('to') => $this->getOptions('from')
				])
				->setTemplate($this->getOptions('template'))
				->setEmailFormat($this->getOptions('format'))
				->setTo($this->getOptions('to'))
				->setSubject($this->getOptions('subject'))
				->send($this->getOptions('message'), $data);
		} catch (\Exception $e) {
			 $this->log($e->getMessage());
		}
	}
	
	
}