<?php
/**
 * Created by PhpStorm.
 * User: snguyenone
 * Date: 9/27/18
 * Time: 19:31
 */
namespace App\Model\Table;

use App\Model\Entity\Message;

class MessagesTable extends AppTable
{
	public function initialize(array $config)
	{
		$this->addBehavior('Timestamp');
		$this->belongsTo('Threads');
	}
	
	public function find($type = 'all', $options = [])
	{
		return parent::find($type, $options); // TODO: Change the autogenerated stub
	}
	
	/**
	 * @param $requestData
	 * @param $messages
	 * @return bool
	 */
	public function saveMessages($requestData = null, Message $messages = null)
	{
		if (empty($messages)) {
			$messages = $this->newEntity();
		}
		
		$messages = $this->patchEntity($messages, $requestData);
		
		return $this->save($messages) ? true : false;
	}
	
	/**
	 * @param $userId
	 * @param $threadId
	 * @param array $condition
	 * @param int $limit
	 * @return \Cake\ORM\Query
	 */
	public function geLastMsgThreadPerUser($userId, $threadId, array $condition = [], $limit = 6)
	{
		return $this
			->find()
			->where($condition)
			->where('Messages.thread_id = '.$threadId .' AND (Messages.user_send_id = ' . $userId . ' OR Messages.user_reply_id = ' .$userId . ')')
			->limit($limit)
			->order(['Messages.created' => 'DESC']);
	}
	
}